name: Build & run tests

on:
  push:
    branches: master

  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      CXX: ${{ matrix.config.compiler }}
      EXECUTABLE: ./delocto

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows Latest GCC",
              os: windows-latest,
              compiler: g++
            }
          - {
              name: "Windows Latest Clang",
              os: windows-latest,
              compiler: clang++
            }
          - {
              name: "Ubuntu Latest GCC",
              os: ubuntu-latest,
              compiler: g++
            }
          - {
              name: "Ubuntu Latest Clang",
              os: ubuntu-latest,
              compiler: clang++
            }
          - {
              name: "macOS Latest Clang",
              os: macos-latest,
              compiler: clang++
            }
    defaults:
      run:
        working-directory: src
        shell: bash
    steps:
      - uses: actions/checkout@master
      
      - name: Print trigger & compiler version
        run: |
          echo Trigger: ${{ github.event_name }}
          $CXX -v

      - name: Build
        run: |
          make

      - name: Benchmark
        run: |
          BENCHMARK=$($EXECUTABLE bench | grep 'Nodes searched (total)' | grep -Eo '[0-9]+')
          COMMIT_BENCHMARK=$(echo "${{ github.event.head_commit.message }}" | grep -Eo '[Bb]ench(mark)?:\s[0-9]+$' | grep -Eo '[0-9]+')
          echo Benchmark: $BENCHMARK
          echo Reference: $COMMIT_BENCHMARK
          if [[ $BENCHMARK != $COMMIT_BENCHMARK ]]; then
            echo Incorrect benchmark!
            exit 1
          else
            echo Matching benchmark!
          fi

      - name: Unit Tests
        working-directory: tests
        run: |
          curl https://raw.githubusercontent.com/catchorg/Catch2/v2.x/single_include/catch2/catch.hpp --output catch.hpp
          make
          ./tests
